config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :restaurants do
    resources :reviews
  end

  root 'restaurants#index'

end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
	validates :name, presence: true, format: { with: /\A[A-Z]/, message: 'must begin with a capital letter'}
	validates :cuisine, presence: true, length: { minimum: 3 }
	has_many :reviews
	belongs_to :user

	def average_rating 
		return 'N/A' if reviews.none?
		reviews.average(:rating)
	end
end

app/models/review.rb
class Review < ActiveRecord::Base
	belongs_to :restaurant
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController

	before_action :authenticate_user!, except: [:index]

	def index
		@restaurants = Restaurant.all
		@review = Review.new
	end

	def new
		@restaurant = Restaurant.new
	end

	def create
		@restaurant = Restaurant.new restaurant_params
		@restaurant.user = current_user

		if @restaurant.save
			redirect_to '/restaurants'
		else
			render 'new'
		end
	end

	def edit
		@restaurant = current_user.restaurants.find(params[:id])
		rescue ActiveRecord::RecordNotFound
		flash[:notice] = 'Not one of your restaurants'
		redirect_to '/restaurants'
	end

	def update
		@restaurant = current_user.restaurants.find(params[:id])
		
		if @restaurant.update restaurant_params
			redirect_to '/restaurants'
		else
			render 'new'
		end
	end

	def destroy
		@restaurant = current_user.restaurants.find(params[:id])
		@restaurant.destroy
		flash[:notice] = "#{@restaurant.name} successfully deleted"

	rescue ActiveRecord::RecordNotFound
		flash[:notice] = 'Not one of your restaurants'
		ensure
		redirect_to '/restaurants'
	end

	# another way if we want to refarctor instead of params[:restaurant].permit(:name)
	private

	def restaurant_params
		params[:restaurant].permit(:name, :cuisine)
	end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
	def new
		@restaurant = Restaurant.find params[:restaurant_id]
		@review = Review.new
	end

	def create
		@restaurant = Restaurant.find params[:restaurant_id]
		@review = @restaurant.reviews.create params[:review].permit(:thoughts, :rating)
		redirect_to '/restaurants' unless request.xhr?
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper

	def star_rating(rating)
		return rating unless rating.respond_to?(:round)

		rounded_rating = rating.round
		('★' * rounded_rating)  + ('☆' * (5-rounded_rating))
	end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Yelpmay</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
      <%= alert %>
	<%= notice %>

	<% if user_signed_in? %>
		<%= link_to('Edit registration', edit_user_registration_path) %>
		<%= link_to('Logout', destroy_user_session_path, :method => :delete) %>
	<% else %>
 		<%= link_to('Register', new_user_registration_path)  %>
 		<%= link_to('Login', new_user_session_path)  %>
	<% end %>

	<%= yield %>

</body>
</html>

app/views/restaurants/_form.html.erb
<% if @restaurant.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@restaurant.errors.count, "error") %> prohibited this post from being saved:</h2>
 
    <ul>
    <% @restaurant.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>
<%= form_for @restaurant do |f| %>

	<%= f.label :name %>
	<%= f.text_field :name, required: true %>

	<%= f.label :cuisine %>
	<%= f.text_field :cuisine, required: true %>

	<%= f.submit %>
<% end %>

app/views/restaurants/edit.html.erb
<%= render 'form' %>

app/views/restaurants/index.html.erb
<% if @restaurants.any? %>
	<ul>
	<% @restaurants.each do |restaurant| %>
		<li class = "restaurant">
			<%= restaurant.name %> (<%=restaurant.cuisine %>)<br> 
			Average rating: <span class = "average_rating"><%= star_rating(restaurant.average_rating) %></span><br>
			<% if user_signed_in? %>
				<%= link_to "Edit #{restaurant.name} ", edit_restaurant_path(restaurant.id) %><br>
				<%= link_to "Delete #{restaurant.name} ", restaurant_path(restaurant.id) , method: :delete , 'data-confirm' => 'Are you sure you want to delete this?'  %><br>
				<ul class="reviews">
					<% restaurant.reviews.each do |review| %>
						<li><%= review.thoughts %> (<%= star_rating(review.rating) %>)</li>
					<% end %>
				</ul>
			<% end %>
			<% if user_signed_in? %>
				<%= form_for [restaurant, @review] do |f| %>

					<%= f.label :thoughts %>
					<%= f.text_area :thoughts %>

					<%= f.label :rating %>
					<%= f.select :rating, 1..5 %>

					<%= f.submit %>
				<% end %>
			<% end %>
		</li>
	<% end %>
	</ul>
<% else %>
	No restaurants yet
	<% end %>

<%= link_to "Create a restaurant", new_restaurant_path %>

app/views/restaurants/new.html.erb
<%= render 'form' %>

app/views/reviews/new.html.erb
<%= form_for [@restaurant, @review] do |f| %>

	<%= f.label :thoughts %>
	<%= f.text_area :thoughts %>

	<%= f.label :rating %>
	<%= f.select :rating, 1..5 %>

	<%= f.submit %>
<% end %>